#!/bin/bash
xorriso -as mkisofs -b limine-bios-cd.bin -no-emul-boot -boot-load-size 4 -boot-info-table --efi-boot limine-uefi-cd.bin -efi-boot-part --efi-boot-image --protective-msdos-label iso_root -o bin/image.iso
# I have to add a comment to have git play nice and push this file with the execute permission...
